organization: # Name of your organization (mandatory)
  name: "My Organization"

database: # Database credentials, must match what you have in the docker-compose (mandatory)
  host: "postgresql"
  port: 5432
  name: "conduktor-console"
  username: "conduktor"
  password: "change_me"

admin: # Define the local admin for the initial setup (mandatory)
  email: admin@conduktor.io
  password: admin

auth: # Define a local user (optional)
  local-users:
    - email: user@conduktor.io
      password: user

monitoring: # Monitoring settings (optional)
  cortex-url: http://conduktor-monitoring:9009/
  alert-manager-url: http://conduktor-monitoring:9010/
  callback-url: http://conduktor-console:8080/monitoring/api/
  notifications-callback-url: http://localhost:8080

clusters: # Cluster and schema registry configuration (optional)
  - id: my-local-kafka-cluster
    name: My Local Kafka Cluster
    bootstrapServers: "broker-1:29092,broker-2:29093,broker-3:29094"
    schemaRegistry:
      url: "http://schema-registry:8081"
#    kafkaConnects:
#      - url: http://kafka-connect:8083
#        name: full stack kafka connect
